import React from 'react';
import { 
  Home, 
  Upload, 
  Package, 
  User, 
  ShoppingCart, 
  Search, 
  Heart, 
  Bell, 
  Settings, 
  Menu,
  Plus,
  Minus,
  Check,
  X,
  ChevronRight,
  ChevronLeft,
  Star,
  Filter,
  Grid,
  List,
  Map,
  Phone,
  Mail,
  Calendar,
  Clock,
  Eye,
  EyeOff,
  Edit,
  Trash,
  Download,
  Share,
  Bookmark,
  MessageCircle,
  HelpCircle,
  Info,
  AlertCircle,
  CheckCircle,
  XCircle,
  Loader,
  RefreshCw,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  Copy,
  Scissors,
  Paperclip,
  Image,
  File,
  FileText,
  Folder,
  FolderOpen,
  Save,
  Printer,
  Camera,
  Video,
  Mic,
  Volume,
  VolumeX,
  Wifi,
  WifiOff,
  Battery,
  BatteryLow,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Zap,
  Shield,
  ShieldCheck,
  Lock,
  Unlock,
  Key,
  UserPlus,
  UserMinus,
  UserCheck,
  Users,
  CreditCard,
  DollarSign,
  TrendingUp,
  TrendingDown,
  BarChart,
  PieChart,
  Activity,
  Target,
  Award,
  Gift,
  Tag,
  Truck,
  MapPin,
  Navigation,
  Compass,
  Globe,
  Bluetooth,
  Headphones,
  Speaker,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Server,
  Database,
  HardDrive,
  Cpu,
  Power,
  PowerOff,
  Plug,
  Cable,
  Router,
  Gamepad2,
  Joystick,
  Dices,
  Puzzle,
  Paintbrush,
  Palette,
  Brush,
  Pen,
  PenTool,
  Type,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Bold,
  Italic,
  Underline,
  Link,
  Unlink,
  Quote,
  Code,
  Terminal,
  Bug,
  GitBranch,
  Github,
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  Youtube,
  Twitch,
  Slack,
  Figma,
  Chrome
} from 'lucide-react';
import { GlassIcon } from './GlassIcon';

// Export all glassmorphism icon variants
export const GlassIcons = {
  // Navigation & UI
  Home: (props: any) => <GlassIcon {...props}><Home className="w-5 h-5" /></GlassIcon>,
  Upload: (props: any) => <GlassIcon {...props}><Upload className="w-5 h-5" /></GlassIcon>,
  Package: (props: any) => <GlassIcon {...props}><Package className="w-5 h-5" /></GlassIcon>,
  User: (props: any) => <GlassIcon {...props}><User className="w-5 h-5" /></GlassIcon>,
  ShoppingCart: (props: any) => <GlassIcon {...props}><ShoppingCart className="w-5 h-5" /></GlassIcon>,
  Search: (props: any) => <GlassIcon {...props}><Search className="w-5 h-5" /></GlassIcon>,
  Menu: (props: any) => <GlassIcon {...props}><Menu className="w-5 h-5" /></GlassIcon>,
  Settings: (props: any) => <GlassIcon {...props}><Settings className="w-5 h-5" /></GlassIcon>,
  
  // Actions
  Plus: (props: any) => <GlassIcon {...props}><Plus className="w-5 h-5" /></GlassIcon>,
  Minus: (props: any) => <GlassIcon {...props}><Minus className="w-5 h-5" /></GlassIcon>,
  Check: (props: any) => <GlassIcon {...props}><Check className="w-5 h-5" /></GlassIcon>,
  X: (props: any) => <GlassIcon {...props}><X className="w-5 h-5" /></GlassIcon>,
  Edit: (props: any) => <GlassIcon {...props}><Edit className="w-5 h-5" /></GlassIcon>,
  Trash: (props: any) => <GlassIcon {...props}><Trash className="w-5 h-5" /></GlassIcon>,
  Save: (props: any) => <GlassIcon {...props}><Save className="w-5 h-5" /></GlassIcon>,
  Download: (props: any) => <GlassIcon {...props}><Download className="w-5 h-5" /></GlassIcon>,
  Share: (props: any) => <GlassIcon {...props}><Share className="w-5 h-5" /></GlassIcon>,
  Copy: (props: any) => <GlassIcon {...props}><Copy className="w-5 h-5" /></GlassIcon>,
  
  // Arrows & Navigation
  ChevronRight: (props: any) => <GlassIcon {...props}><ChevronRight className="w-5 h-5" /></GlassIcon>,
  ChevronLeft: (props: any) => <GlassIcon {...props}><ChevronLeft className="w-5 h-5" /></GlassIcon>,
  ArrowUp: (props: any) => <GlassIcon {...props}><ArrowUp className="w-5 h-5" /></GlassIcon>,
  ArrowDown: (props: any) => <GlassIcon {...props}><ArrowDown className="w-5 h-5" /></GlassIcon>,
  ArrowLeft: (props: any) => <GlassIcon {...props}><ArrowLeft className="w-5 h-5" /></GlassIcon>,
  ArrowRight: (props: any) => <GlassIcon {...props}><ArrowRight className="w-5 h-5" /></GlassIcon>,
  
  // Status & Feedback
  Heart: (props: any) => <GlassIcon {...props}><Heart className="w-5 h-5" /></GlassIcon>,
  Star: (props: any) => <GlassIcon {...props}><Star className="w-5 h-5" /></GlassIcon>,
  Bell: (props: any) => <GlassIcon {...props}><Bell className="w-5 h-5" /></GlassIcon>,
  AlertCircle: (props: any) => <GlassIcon {...props}><AlertCircle className="w-5 h-5" /></GlassIcon>,
  CheckCircle: (props: any) => <GlassIcon {...props}><CheckCircle className="w-5 h-5" /></GlassIcon>,
  XCircle: (props: any) => <GlassIcon {...props}><XCircle className="w-5 h-5" /></GlassIcon>,
  Info: (props: any) => <GlassIcon {...props}><Info className="w-5 h-5" /></GlassIcon>,
  HelpCircle: (props: any) => <GlassIcon {...props}><HelpCircle className="w-5 h-5" /></GlassIcon>,
  
  // Media & Content
  Eye: (props: any) => <GlassIcon {...props}><Eye className="w-5 h-5" /></GlassIcon>,
  EyeOff: (props: any) => <GlassIcon {...props}><EyeOff className="w-5 h-5" /></GlassIcon>,
  Camera: (props: any) => <GlassIcon {...props}><Camera className="w-5 h-5" /></GlassIcon>,
  Video: (props: any) => <GlassIcon {...props}><Video className="w-5 h-5" /></GlassIcon>,
  Image: (props: any) => <GlassIcon {...props}><Image className="w-5 h-5" /></GlassIcon>,
  File: (props: any) => <GlassIcon {...props}><File className="w-5 h-5" /></GlassIcon>,
  FileText: (props: any) => <GlassIcon {...props}><FileText className="w-5 h-5" /></GlassIcon>,
  Folder: (props: any) => <GlassIcon {...props}><Folder className="w-5 h-5" /></GlassIcon>,
  
  // Communication
  Phone: (props: any) => <GlassIcon {...props}><Phone className="w-5 h-5" /></GlassIcon>,
  Mail: (props: any) => <GlassIcon {...props}><Mail className="w-5 h-5" /></GlassIcon>,
  MessageCircle: (props: any) => <GlassIcon {...props}><MessageCircle className="w-5 h-5" /></GlassIcon>,
  
  // Time & Calendar
  Calendar: (props: any) => <GlassIcon {...props}><Calendar className="w-5 h-5" /></GlassIcon>,
  Clock: (props: any) => <GlassIcon {...props}><Clock className="w-5 h-5" /></GlassIcon>,
  
  // Layout & View
  Grid: (props: any) => <GlassIcon {...props}><Grid className="w-5 h-5" /></GlassIcon>,
  List: (props: any) => <GlassIcon {...props}><List className="w-5 h-5" /></GlassIcon>,
  Filter: (props: any) => <GlassIcon {...props}><Filter className="w-5 h-5" /></GlassIcon>,
  
  // Location & Maps
  Map: (props: any) => <GlassIcon {...props}><Map className="w-5 h-5" /></GlassIcon>,
  MapPin: (props: any) => <GlassIcon {...props}><MapPin className="w-5 h-5" /></GlassIcon>,
  Navigation: (props: any) => <GlassIcon {...props}><Navigation className="w-5 h-5" /></GlassIcon>,
  Compass: (props: any) => <GlassIcon {...props}><Compass className="w-5 h-5" /></GlassIcon>,
  Globe: (props: any) => <GlassIcon {...props}><Globe className="w-5 h-5" /></GlassIcon>,
  
  // Security & Privacy
  Lock: (props: any) => <GlassIcon {...props}><Lock className="w-5 h-5" /></GlassIcon>,
  Unlock: (props: any) => <GlassIcon {...props}><Unlock className="w-5 h-5" /></GlassIcon>,
  Key: (props: any) => <GlassIcon {...props}><Key className="w-5 h-5" /></GlassIcon>,
  Shield: (props: any) => <GlassIcon {...props}><Shield className="w-5 h-5" /></GlassIcon>,
  ShieldCheck: (props: any) => <GlassIcon {...props}><ShieldCheck className="w-5 h-5" /></GlassIcon>,
  
  // E-commerce & Business
  CreditCard: (props: any) => <GlassIcon {...props}><CreditCard className="w-5 h-5" /></GlassIcon>,
  DollarSign: (props: any) => <GlassIcon {...props}><DollarSign className="w-5 h-5" /></GlassIcon>,
  Tag: (props: any) => <GlassIcon {...props}><Tag className="w-5 h-5" /></GlassIcon>,
  Gift: (props: any) => <GlassIcon {...props}><Gift className="w-5 h-5" /></GlassIcon>,
  Truck: (props: any) => <GlassIcon {...props}><Truck className="w-5 h-5" /></GlassIcon>,
  
  // Charts & Analytics
  TrendingUp: (props: any) => <GlassIcon {...props}><TrendingUp className="w-5 h-5" /></GlassIcon>,
  TrendingDown: (props: any) => <GlassIcon {...props}><TrendingDown className="w-5 h-5" /></GlassIcon>,
  BarChart: (props: any) => <GlassIcon {...props}><BarChart className="w-5 h-5" /></GlassIcon>,
  PieChart: (props: any) => <GlassIcon {...props}><PieChart className="w-5 h-5" /></GlassIcon>,
  Activity: (props: any) => <GlassIcon {...props}><Activity className="w-5 h-5" /></GlassIcon>,
  Target: (props: any) => <GlassIcon {...props}><Target className="w-5 h-5" /></GlassIcon>,
  
  // System & Loading
  Loader: (props: any) => <GlassIcon {...props}><Loader className="w-5 h-5 animate-spin" /></GlassIcon>,
  Refresh: (props: any) => <GlassIcon {...props}><RefreshCw className="w-5 h-5" /></GlassIcon>,
  Power: (props: any) => <GlassIcon {...props}><Power className="w-5 h-5" /></GlassIcon>,
  PowerOff: (props: any) => <GlassIcon {...props}><PowerOff className="w-5 h-5" /></GlassIcon>,
  
  // Weather & Environment
  Sun: (props: any) => <GlassIcon {...props}><Sun className="w-5 h-5" /></GlassIcon>,
  Moon: (props: any) => <GlassIcon {...props}><Moon className="w-5 h-5" /></GlassIcon>,
  Cloud: (props: any) => <GlassIcon {...props}><Cloud className="w-5 h-5" /></GlassIcon>,
  CloudRain: (props: any) => <GlassIcon {...props}><CloudRain className="w-5 h-5" /></GlassIcon>,
  Zap: (props: any) => <GlassIcon {...props}><Zap className="w-5 h-5" /></GlassIcon>,
  
  // Devices & Technology
  Smartphone: (props: any) => <GlassIcon {...props}><Smartphone className="w-5 h-5" /></GlassIcon>,
  Tablet: (props: any) => <GlassIcon {...props}><Tablet className="w-5 h-5" /></GlassIcon>,
  Laptop: (props: any) => <GlassIcon {...props}><Laptop className="w-5 h-5" /></GlassIcon>,
  Monitor: (props: any) => <GlassIcon {...props}><Monitor className="w-5 h-5" /></GlassIcon>,
  Headphones: (props: any) => <GlassIcon {...props}><Headphones className="w-5 h-5" /></GlassIcon>,
  
  // Audio & Volume
  Volume: (props: any) => <GlassIcon {...props}><Volume className="w-5 h-5" /></GlassIcon>,
  VolumeX: (props: any) => <GlassIcon {...props}><VolumeX className="w-5 h-5" /></GlassIcon>,
  Mic: (props: any) => <GlassIcon {...props}><Mic className="w-5 h-5" /></GlassIcon>,
  Speaker: (props: any) => <GlassIcon {...props}><Speaker className="w-5 h-5" /></GlassIcon>,
  
  // Connectivity
  Wifi: (props: any) => <GlassIcon {...props}><Wifi className="w-5 h-5" /></GlassIcon>,
  WifiOff: (props: any) => <GlassIcon {...props}><WifiOff className="w-5 h-5" /></GlassIcon>,
  Bluetooth: (props: any) => <GlassIcon {...props}><Bluetooth className="w-5 h-5" /></GlassIcon>,
  
  // Users & People
  Users: (props: any) => <GlassIcon {...props}><Users className="w-5 h-5" /></GlassIcon>,
  UserPlus: (props: any) => <GlassIcon {...props}><UserPlus className="w-5 h-5" /></GlassIcon>,
  UserMinus: (props: any) => <GlassIcon {...props}><UserMinus className="w-5 h-5" /></GlassIcon>,
  UserCheck: (props: any) => <GlassIcon {...props}><UserCheck className="w-5 h-5" /></GlassIcon>,
  
  // Development & Code
  Code: (props: any) => <GlassIcon {...props}><Code className="w-5 h-5" /></GlassIcon>,
  Terminal: (props: any) => <GlassIcon {...props}><Terminal className="w-5 h-5" /></GlassIcon>,
  Bug: (props: any) => <GlassIcon {...props}><Bug className="w-5 h-5" /></GlassIcon>,
  GitBranch: (props: any) => <GlassIcon {...props}><GitBranch className="w-5 h-5" /></GlassIcon>,
  
  // Text Formatting
  Bold: (props: any) => <GlassIcon {...props}><Bold className="w-5 h-5" /></GlassIcon>,
  Italic: (props: any) => <GlassIcon {...props}><Italic className="w-5 h-5" /></GlassIcon>,
  Underline: (props: any) => <GlassIcon {...props}><Underline className="w-5 h-5" /></GlassIcon>,
  Type: (props: any) => <GlassIcon {...props}><Type className="w-5 h-5" /></GlassIcon>,
  
  // Links & External
  Link: (props: any) => <GlassIcon {...props}><Link className="w-5 h-5" /></GlassIcon>,
  Unlink: (props: any) => <GlassIcon {...props}><Unlink className="w-5 h-5" /></GlassIcon>,
  ExternalLink: (props: any) => <GlassIcon {...props}><ExternalLink className="w-5 h-5" /></GlassIcon>,
  
  // Achievement & Gamification
  Award: (props: any) => <GlassIcon {...props}><Award className="w-5 h-5" /></GlassIcon>,
  Bookmark: (props: any) => <GlassIcon {...props}><Bookmark className="w-5 h-5" /></GlassIcon>,
};

// Default export for convenience
export default GlassIcons;